### ISSUE TITLE
Weather Display Issue: "Feels" & "Earth" Shown Instead of Actual Location

### ISSUE THREAD

**Issue by XengShi** [XengShi/materialYouNewTab#84] opened 2024-10-20 18:11 UTC
We are experiencing weather-related issues. After opening the browser or a new tab, it always shows 'Feels' and 'Earth' instead of the actual location and the feels-like temperature. However, refreshing the tab by pressing Ctrl + Shift + R displays the information correctly.
I suspect that some translation code may be affecting this.

I am getting this in Chrome (Checked on Windows)
for Firefox it works fine. 

@prem12321kumar @itz-rj-here @Minuga-RC

**Comment by Minuga-RC** [comment] 2024-10-20 18:17
This is not because of translation code it's because of that api you guys have used to get the current location information it sometimes just gets ratelimited or something and just refuses to give the location and because of that weather api get confused and returns nothing

**Comment by Minuga-RC** [comment] 2024-10-20 18:18
I will look into an another way of getting location info in the rewrite v3 I'm making rn

**Comment by Minuga-RC** [comment] 2024-10-20 18:22
I will make a temporarily fix for now tomorrow 
By saving the location in local storage @XengShi

**Comment by XengShi** [comment] 2024-10-20 18:24
Even gettting on firefox too.

https://github.com/user-attachments/assets/4273d3c4-5187-47ca-9971-e172450985ee

@Minuga-RC Thanks for figuring it out, Good night 😴

**Comment by ceskyDJ** [comment] 2024-10-20 18:25
Hmm, it works well for me (with Brno set via GPS coordinates).

**Comment by prem12321kumar** [comment] 2024-10-20 20:10
> We are experiencing weather-related issues. After opening the browser or a new tab, it always shows 'Feels' and 'Earth' instead of the actual location and the feels-like temperature. However, refreshing the tab by pressing Ctrl + Shift + R displays the information correctly. I suspect that some translation code may be affecting this.
> 
> I am getting this in Chrome (Checked on Windows) for Firefox it works fine.
> 
> @prem12321kumar @itz-rj-here @Minuga-RC


yeah, I also think this might be of some translation code. 
I cant recreate this bug but from video 0.33, it's not that unable to fetch weather data, it's showing temp an₫ humidity. 
if so then commenting this two translating lines should temp fix this for now.
I will check tommorow.

**Comment by prem12321kumar** [comment] 2024-10-21 05:06
@XengShi Please check if the issue is fixed and it's translating

**Comment by prem-k-r** [comment] 2024-11-03 09:32
@XengShi fixed in general?

**Comment by itz-rj-here** [comment] 2024-11-03 09:52
i think.

**Comment by XengShi** [comment] 2024-11-03 16:25
[Screencast from 2024-11-03 13-25-26.webm](https://github.com/user-attachments/assets/d42951d1-d424-4e41-b3cd-9b2392840af0)

Still need to be fixed!

**Comment by prem-k-r** [comment] 2024-11-03 16:37
Yes, in case of using any custom shortcut. 

> Screencast.from.2024-11-03.13-25-26.webm 
> Still need to be fixed!

**Comment by XengShi** [comment] 2024-11-03 16:45
> Yes, in case of using any custom shortcut. 
> 
> > Screencast.from.2024-11-03.13-25-26.webm 
> > Still need to be fixed!
> 
> 

Yes, but this will not entertain the users who are most likely to add their own shortcuts!

**Comment by prem-k-r** [comment] 2024-11-03 17:36
> > Yes, in case of using any custom shortcut.
> > > Screencast.from.2024-11-03.13-25-26.webm
> > > Still need to be fixed!
> 
> Yes, but this will not entertain the users who are most likely to add their own shortcuts!

const FAVICON_CANDIDATES = (hostname) => [
        `https://${hostname}/apple-touch-icon-180x180.png`,
        `https://${hostname}/apple-touch-icon-120x120.png`,
        `https://${hostname}/apple-touch-icon.png`
    ];
    
    removing this and related snippet fixes the issse. but I dont understand why.

**Comment by itz-rj-here** [comment] 2024-11-04 01:06
What you guys want to say. like when using the custom shortcuts the weather and feels doesn’t work properly.? 
Then mention the contributor who modified the shortcuts menu. Request him to look into it. If needed.

**Closed** 2024-11-08 11:03 UTC
